# The purpose of this program is to simulate a neural network based orbital system.
# It renders planetary motion using AI-predicted state vectors and visualizes trajectories in real time.

import pygame
import numpy as np
import joblib
import os
import sys
import math
import pygame_widgets
from pygame_widgets.slider import Slider
from pygame_widgets.textbox import TextBox
from pygame_widgets.button import Button
from tensorflow.keras.models import load_model
from nasaData import real_states_array  # initial planetary state data used for simulation

# --- PYGAME SETUP ---
# The purpose of this section is to initialize the graphical simulation environment.
pygame.init()

WIDTH, HEIGHT = 1200, 800
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Orbital AI - Natural Solar System")

clock = pygame.time.Clock()

# fonts used for UI rendering
font = pygame.font.SysFont("Arial", 18)
title_font = pygame.font.SysFont("Arial", 28, bold=True)

# basic color definitions used throughout rendering
BLACK, WHITE, GRAY = (0, 0, 0), (255, 255, 255), (150, 150, 150)

# colors assigned to each planet for visualization consistency
PLANET_COLORS = [
    (255, 215, 0), (176, 196, 222), (255, 165, 0), (65, 105, 225),
    (255, 69, 0), (221, 160, 221), (244, 164, 96), (224, 255, 255), (0, 0, 205)
]

# names of celestial bodies in the simulation
PLANET_NAMES = ['Sun', 'Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

# visual size scaling for each planet (not physically accurate)
PLANET_SIZES = [12, 3, 4, 4, 3, 8, 7, 5, 5]

camera_x, camera_y = 0.0, 0.0  # camera offset for panning
zoom = 1.5  # zoom level for visualization

# The purpose of this section is to load the trained neural network and preprocessing tools.
print("Loading AI Model and Scalers...")
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

try:
    # loads trained neural network model
    model = load_model(os.path.join(BASE_DIR, "solar_system_ai.keras"))

    # loads feature scaling objects used during training
    X_scaler = joblib.load(os.path.join(BASE_DIR, "X_scaler.pkl"))
    y_scaler = joblib.load(os.path.join(BASE_DIR, "y_scaler.pkl"))

except Exception as e:
    print(f"Failed to load model/scalers: {e}")
    sys.exit()

# converts initial planetary dataset into structured numerical array
real_states_array = np.array(real_states_array).reshape(-1, 6)
num_bodies = real_states_array.shape[0]

# stores predicted frames generated by neural network
frame_queue = []
global_day = 1

#         State variables
# Simulation starts paused to allow user to adjust settings first
is_paused = True
current_frame = None 

# maximum number of trail points stored per planet
MAX_TRAIL_LENGTH = 300
# stores historical positions for orbit rendering
trail_history = {i: [] for i in range(num_bodies)}

# generates background starfield for visual effect
num_stars = 200
stars = [
    (np.random.randint(0, WIDTH),
     np.random.randint(0, HEIGHT),
     np.random.randint(1, 3))
    for _ in range(num_stars)
]

# The purpose of this function is to convert world-space coordinates into screen-space coordinates.
def world_to_screen(x, y):
    distance = math.hypot(x, y)

    if distance == 0:
        scaled_x, scaled_y = 0, 0
    else:
        angle = math.atan2(y, x)
        # compresses astronomical distances for visualization
        scaled_distance = (distance ** 0.35) * 0.02 * zoom
        scaled_x = scaled_distance * math.cos(angle)
        scaled_y = scaled_distance * math.sin(angle)

    screen_x = int(WIDTH / 2 + scaled_x + camera_x)
    screen_y = int(HEIGHT / 2 - scaled_y + camera_y)
    return screen_x, screen_y

# The purpose of this function is to render a planet with a glowing visual effect.
def draw_glowing_planet(surface, color, pos, radius):
    glow_radius = radius * 3
    glow_surf = pygame.Surface((glow_radius * 2, glow_radius * 2), pygame.SRCALPHA)

    # outer glow layer
    pygame.draw.circle(glow_surf, (*color, 30), (glow_radius, glow_radius), glow_radius)
    # inner glow layer
    pygame.draw.circle(glow_surf, (*color, 100), (glow_radius, glow_radius), int(radius * 1.5))
    # solid planet body
    pygame.draw.circle(glow_surf, color, (glow_radius, glow_radius), radius)

    surface.blit(glow_surf, (pos[0] - glow_radius, pos[1] - glow_radius))

# The purpose of this function is to render text labels onto the screen.
def draw_text(text, x, y, color=WHITE, is_title=False):
    f = title_font if is_title else font
    surface = f.render(text, True, color)
    screen.blit(surface, (x, y))

# The purpose of this section is to simulate an external gravitational object.
Interloper_Mass = 6e23
Interloper_Pos = [4e11, 4e11, 0]
Interloper_Vel = [-45000, -35000, 0]

#  UI WIDGETS 
ui_x = 20
# Mass slider limited to 10^20 minimum (min=200 since it is divided by 10)
mass_slider = Slider(screen, ui_x, 150, 200, 15, min=200, max=500, step=1, initial=247)
angle_slider = Slider(screen, ui_x, 210, 200, 15, min=0, max=360, step=1, initial=215)
speed_slider = Slider(screen, ui_x, 270, 200, 15, min=0, max=100000, step=1000, initial=57000)

def toggle_pause():
    global is_paused
    is_paused = not is_paused

def apply_new_physics():
    global Interloper_Mass, Interloper_Vel, global_day, frame_queue, trail_history, is_paused, current_frame
    
    actual_mass_exponent = mass_slider.getValue() / 10.0
    Interloper_Mass = 10 ** actual_mass_exponent
    
    angle_degrees = angle_slider.getValue()
    speed = speed_slider.getValue()
    angle_radians = math.radians(angle_degrees)
    
    Interloper_Vel[0] = speed * math.cos(angle_radians)
    Interloper_Vel[1] = speed * math.sin(angle_radians)
    
    global_day = 1
    frame_queue.clear()
    current_frame = None  # Triggers a reload of the first frame
    is_paused = True      # Reset simulation to paused state
    
    for i in range(num_bodies):
        trail_history[i].clear()

pause_button = Button(
    screen, ui_x, 320, 150, 40, text='Pause / Play',
    fontSize=22, margin=20, inactiveColour=(200, 200, 100),
    pressedColour=(150, 150, 50), radius=10,
    onClick=toggle_pause 
)

reset_button = Button(
    screen, ui_x, 370, 150, 40, text='Apply & Reset',
    fontSize=22, margin=20, inactiveColour=(100, 200, 100),
    pressedColour=(50, 150, 50), radius=10,
    onClick=apply_new_physics 
)

# The purpose of this function is to generate batched model inputs for future simulation frames.
def generate_batch(start_day, batch_size=50):
    start_x, start_y, start_z = Interloper_Pos
    vel_x, vel_y, vel_z = Interloper_Vel

    initial_distances = []
    for i in range(num_bodies):
        bx, by, bz = real_states_array[i][:3]
        initial_distances.append(np.linalg.norm([start_x - bx, start_y - by, start_z - bz]))

    raw_inputs = [Interloper_Mass, 1, start_x, start_y, start_z,
                  vel_x, vel_y, vel_z] + initial_distances

    X_base = np.array(raw_inputs, dtype=float)
    X_base[0] = np.log10(Interloper_Mass)

    batch_inputs = []
    ghost_positions = []

    for day in range(start_day, start_day + batch_size):
        temp = X_base.copy()
        temp[1] = day 
        gx = start_x + vel_x * day * 86400
        gy = start_y + vel_y * day * 86400
        batch_inputs.append(temp)
        ghost_positions.append((gx, gy))

    X_scaled = X_scaler.transform(np.array(batch_inputs))
    y_scaled = model.predict(X_scaled, verbose=0)
    predicted_states = y_scaler.inverse_transform(y_scaled)

    frames = [
        {
            "day": start_day + i,
            "y_real": predicted_states[i],
            "ghost_pos": ghost_positions[i]
        }
        for i in range(batch_size)
    ]
    return frames

# The purpose of this section is to continuously update and render the orbital simulation.
running = True
print("Starting simulation...")

while running:
    events = pygame.event.get()
    screen.fill((5, 5, 15))

    # draws background stars
    for star_x, star_y, star_size in stars:
        pygame.draw.circle(screen, (200, 200, 200), (star_x, star_y), star_size)

    # handles user input events
    for event in events:
        if event.type == pygame.QUIT:
            running = False
            
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_SPACE:
                is_paused = not is_paused
                
        if event.type == pygame.MOUSEWHEEL:
            zoom *= 1.1 if event.y > 0 else 0.9
        elif event.type == pygame.MOUSEMOTION:
            if pygame.mouse.get_pressed()[0] and event.pos[0] > 350:
                camera_x += event.rel[0]
                camera_y += event.rel[1]

    # fetches new frames if simulation is active OR if current_frame is missing (after reset)
    if current_frame is None or not is_paused:
        if len(frame_queue) < 10:
            frame_queue.extend(generate_batch(global_day, batch_size=50))
            global_day += 50
        current_frame = frame_queue.pop(0)

    # UI overlay
    status_text = f"Day: {current_frame['day']} (PAUSED)" if is_paused else f"Day: {current_frame['day']}"
    draw_text(status_text, 20, 20, color=(255,100,100) if is_paused else WHITE, is_title=True)
    draw_text("Scroll: Zoom | Drag: Pan | Spacebar: Pause", 20, 60, GRAY)
    draw_text(f"Zoom Level: {zoom:.2f}x", 20, 90, GRAY)

    # renders planets and orbital trails
    for i in range(num_bodies):
        px, py = current_frame['y_real'][i*6], current_frame['y_real'][i*6 + 1]

        if not is_paused:
            trail_history[i].append((px, py))
            if len(trail_history[i]) > MAX_TRAIL_LENGTH:
                trail_history[i].pop(0)

        screen_trail = [world_to_screen(tx, ty) for tx, ty in trail_history[i]]
        if len(screen_trail) >= 2:
            pygame.draw.lines(screen, PLANET_COLORS[i], False, screen_trail, 1)

        sx, sy = world_to_screen(px, py)
        size = max(2, int(PLANET_SIZES[i] * math.sqrt(zoom)))
        draw_glowing_planet(screen, PLANET_COLORS[i], (sx, sy), size)
        draw_text(PLANET_NAMES[i], sx + 15, sy - 15, WHITE)

    # renders rogue object
    gx, gy = current_frame['ghost_pos']
    screen_gx, screen_gy = world_to_screen(gx, gy)
    
    pygame.draw.circle(screen, (255, 50, 50), (screen_gx, screen_gy), 6)
    draw_text("Rogue Object", screen_gx + 15, screen_gy - 15, (255, 50, 50))

    # renders trajectory preview line when paused
    if is_paused:
        preview_angle = math.radians(angle_slider.getValue())
        line_length = 40 + (speed_slider.getValue() / 100000) * 150 
        end_x = screen_gx + math.cos(preview_angle) * line_length
        end_y = screen_gy - math.sin(preview_angle) * line_length
        pygame.draw.line(screen, (255, 100, 100), (screen_gx, screen_gy), (end_x, end_y), 3)
        pygame.draw.circle(screen, (255, 100, 100), (int(end_x), int(end_y)), 5, 1)

    # live UI Labels
    actual_mass_exponent = mass_slider.getValue() / 10.0
    draw_text(f"Mass: 10^{actual_mass_exponent:.1f} kg", ui_x + 220, 145)
    draw_text(f"Angle: {angle_slider.getValue()}°", ui_x + 220, 205)
    draw_text(f"Speed: {speed_slider.getValue()} m/s", ui_x + 220, 265)

    pygame_widgets.update(events)
    pygame.display.flip()
    clock.tick(60)

pygame.quit()